### ISSUE TITLE
Error: Table must define at least one row.

### ISSUE THREAD

**Issue by bybatkhuu** [sinedied/publish-devto-template#3]
Hello, @sinedied

I've tried to use your **devto-github-template** as a template repo.
And added **DEVTO_TOKEN** from **dev.to** to repo secret.

But when I try to run the **publish** action, it gives these errors:

```txt
Run sinedied/publish-devto@v[2](https://github.com/bybatkhuu/devto-github/runs/5860809357?check_suite_focus=true#step:3:2)
  with:
    devto_key: ***
    github_token: ***
    files: posts/**/*.md
    branch: main
    conventional_commits: true
    dry_run: false
Found 1 article(s)
- Retrieving articles from dev.to…
Error: Cannot find published article on dev.to: Example article title
Push failed

Error: Error: Table must define at least one row.
```

What does it mean: **Error: Table must define at least one row.**?

Artice table already exists in **posts/example.md** file, right?

Is there anything did I miss?

**Comment by sinedied** [comment]
You have to look at the first error here: `Error: Cannot find published article on dev.to: Example article title`
This is because the example.md already have an ID as it's published from the CI for testing, but not on your account.
If you remove the id from the md file like your did in PR #4 it will work fine.

The second error is due to the recap logs, and that's something that need to be fixed on the GitHub Actions, I've opened an issue here: https://github.com/sinedied/publish-devto/issues/24
